services:
  - type: web
    name: semgrep-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true