services:
  - type: web
    name: semgrep-analysis-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: semgrep-analysis-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: semgrep-analysis-db
    databaseName: semgrep_analysis
    plan: free