services:
  - type: web
    name: semgrep-analysis-api
    env: python
    region: ohio
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y git curl
      
      # Install Python dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Install semgrep directly (ensure specific version)
      python -m pip install semgrep==1.56.0
      
      # Verify installations
      semgrep --version
      python --version
      
    startCommand: gunicorn --config gunicorn_config.py app:app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: semgrep-analysis-db
          property: connectionString
    autoDeploy: true